services:
  iris-backend:
    build: ./backend
    container_name: iris-server
    ports:
      - "52773:52773"
    volumes:
      # Map your code so ZPM can load it
      - ./:/home/irisowner/dev
    # We remove the ISC_DATA_DIRECTORY and the named volume logic

  angular-frontend:
    build: ./frontend
    container_name: angular-ui
    ports:
      - "8080:80"
    depends_on:
      - iris-backend
